services:

  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mavis" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: mavis_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST:
      DB_NAME:
      DB_USER:
      DB_PASSWORD:
      MAIL_HOST:
      MAIL_PORT:
      MAIL_USERNAME:
      MAIL_PASSWORD:
      TWILIO_ACCOUNT_SID:
      TWILIO_AUTH_TOKEN:
      TWILIO_PHONE_NUMBER:
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
